apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: threatsense
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata        # avoids "lost+found" issue with NFS root
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "threatsense"]
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "threatsense"]
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
      - name: initdb
        configMap:
          name: postgres-initdb
