apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-external
  namespace: threatsense
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.10.200"
spec:
  type: LoadBalancer
  selector:
    app: mqtt-broker
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mqtt-tls
    port: 8883
    targetPort: 8883
    protocol: TCP
