apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: threatsense
spec:
  storageClassName: nfs
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
