apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-gateway
  namespace: threatsense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensor-gateway
  template:
    metadata:
      labels:
        app: sensor-gateway
    spec:
      containers:
      - name: sensor-gateway
        image: 192.168.10.201:5000/threatsense/sensor-gateway:latest
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8081
          name: http
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: sensor-gateway-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "1"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 30
